final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('recipes/', include('recipes.urls')),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += [
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'
urlpatterns = [
    path('', views.RecipeList.as_view(), name="recipe_list"),
    path('<int:pk>/', views.RecipeDetail.as_view(), name='detail'),
    path('add_recipe/', views.add_recipe, name="add_recipe"),
    path('delete/<int:pk>', views.delete_recipe, name="delete_recipe"),
    path('edit/<int:pk>/', views.RecipeUpdateView.as_view(), name='edit_recipe'),
    path('random/', views.random_recipe, name='random_recipe'),
]

final_project/recipes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


def get_default_user_id():
    first_user = User.objects.first()
    if first_user:
        return first_user.pk
    return None


class RecipeCategory(models.Model):
    name = models.CharField(max_length=100)


class Ingredient(models.Model):
    name = models.CharField(max_length=100)


class Instruction(models.Model):
    instruction = models.CharField(max_length=300)


class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=get_default_user_id)
    title = models.CharField(max_length=200)
    ingredients = models.ManyToManyField(Ingredient, through='RecipeIngredient', blank=True)
    instructions = models.ManyToManyField(Instruction, through='RecipeInstruction', blank=True)
    category = models.ForeignKey(RecipeCategory, on_delete=models.CASCADE, blank=True)
    recipe_image = models.CharField(max_length=500, default='https://t4.ftcdn.net/jpg/02/15/28/55/360_F_215285525_fqG9SPnXZfOrwFxHzqI6d1hHPVmdSUSx.jpg')

    def __str__(self):
        return self.title


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)


class RecipeInstruction(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    instruction = models.ForeignKey(Instruction, on_delete=models.CASCADE)

final_project/recipes/forms.py
import requests
from bs4 import BeautifulSoup
from django import forms
from .models import Recipe, Ingredient, Instruction
from django.http import HttpResponseRedirect


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'category', 'recipe_image']


class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['name']


class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        fields = ['instruction']

final_project/recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from bs4 import BeautifulSoup
import requests
from .models import *
from .forms import *
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic import UpdateView
from django.urls import reverse_lazy
import re
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from .mixins import RedirectToLoginMixin
from django.db.models import Q
from django.urls import reverse
from random import choice
from django.contrib import messages


class RecipeList(RedirectToLoginMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipe_list.html'
    context_object_name = 'recipe_list'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = RecipeCategory.objects.all()
        return context

    def get_queryset(self):
        queryset = Recipe.objects.filter(user=self.request.user)
        ingredient_query = self.request.GET.get('ingredient')
        if ingredient_query:
            queryset = queryset.filter(ingredients__name__icontains=ingredient_query)
            return queryset.distinct()
        category_id = self.request.GET.get('category')
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        return queryset


class RecipeDetail(DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'
    context_object_name = 'recipe'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.get_object()
        context['instructions'] = Instruction.objects.filter(recipe=recipe)
        context['ingredients'] = Ingredient.objects.filter(recipe=recipe)
        context['recipe_ingredients'] = RecipeIngredient.objects.filter(recipe=recipe)
        context['recipe_instructions'] = RecipeInstruction.objects.filter(recipe=recipe)
        return context


def add_recipe(request):
    if request.method == 'POST':
        validator = URLValidator()
        recipe_url = request.POST.get('recipe_url')
        if not recipe_url.startswith(('http://', 'https://')):
            recipe_url = 'http://' + recipe_url
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        try:
            response = requests.get(recipe_url, headers=headers)
            response.raise_for_status()
            page = response.content
            soup = BeautifulSoup(page, 'html.parser')
        except requests.RequestException:
            error_message = "URL is not reachable. Please enter a valid URL."
            return render(request, 'recipes/error.html', {'error_message': error_message})
        try:
            validator(recipe_url)
        except ValidationError:
            error_message = "Invalid URL. Please enter a valid URL."
            render(request, 'recipes/error.html', {'error_message': error_message})

        category_id = request.POST.get('category')
        category = RecipeCategory.objects.get(pk=category_id)
        print(category)

        # Extract Recipe object fields
        main = soup.find('main')
        if not main:
            main = soup.find('body')
        # title_tag = main.find(['h1', 'h2'])
        # title = title_tag.text.strip()  # if title_tag else "Untitled"
        header_divs = main.find_all('div', class_=re.compile('.*header.*'))
        print(header_divs)
        title = None
        for div in header_divs:
            head = div.find(['h1', 'h2'])
            if head:
                title = head.text.strip()
                break
            elif div.name in ['div', 'article']:
                print(div)
                head = div.find(['h1', 'h2'])
                if head:
                    title = head.text.strip()
                    break
        if title is None:
            header_div = main.find('header')
            title_tag = header_div.find(['h1', 'h2'])
            if title_tag:
                title = title_tag.text.strip()
            else:
                title = "Untitled Recipe"

        image = main.find('img')
        recipe_image = image['src']

        # Extract ingredients
        ingredients_list = []
        ingredients_div = soup.find('div', class_=re.compile('.*ingredient.*'))
        if ingredients_div:
            list_items = ingredients_div.find_all('li')
        else:
            error_message = f"Cannot import ingredients"
            return render(request, 'recipes/error.html', {'error_message': error_message})

        for li in list_items:
            ingredient_name = li.get_text().strip()
            existing_ingredient = Ingredient.objects.filter(name=ingredient_name).first()
            if existing_ingredient:
                ingredient = existing_ingredient
            else:
                ingredient = Ingredient.objects.create(name=ingredient_name)
            print(ingredient)

            ingredients_list.append(ingredient)

        # Extract Instructions
        instructions_list = []
        instructions_div = soup.find('div', class_=re.compile('.*instruction.*'))
        if not instructions_div:
            error_message = f"Cannot import instructions"
            return render(request, 'recipes/error.html', {'error_message': error_message})
        instruction_items = instructions_div.find_all('li')
        for item in instruction_items:
            instruction_text = item.get_text().strip()
            instruction = Instruction.objects.create(instruction=instruction_text)
            print(instruction)
            instructions_list.append(instruction)

        # Create the Recipe object
        new_recipe = Recipe.objects.create(
            title=title,
            category=category,
            recipe_image=recipe_image
        )

        # create instruction objects
        recipe_instructions = []
        for instruction in instructions_list:
            recipe_instruction = RecipeInstruction.objects.create(
                recipe=new_recipe,
                instruction=instruction
            )
            print(recipe_instruction.instruction)
            recipe_instructions.append(recipe_instruction)

        # Create RecipeIngredient objects for each ingredient
        recipe_ingredients = []
        for ingredient in ingredients_list:
            recipe_ingredient = RecipeIngredient.objects.create(
                recipe=new_recipe,
                ingredient=ingredient
            )
            print(ingredient.name)
            recipe_ingredients.append(recipe_ingredient)
        print('new recipe object created')

        return render(request, 'recipes/recipe_detail.html', {'recipe': new_recipe,
                                                              'recipe_ingredients': recipe_ingredients,
                                                              'recipe_instructions': recipe_instructions})

    else:
        categories = RecipeCategory.objects.all()
        return render(request, 'recipes/add_recipe.html', {'categories': categories})


def delete_recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    if request.method == 'POST':
        recipe.delete()
        print('recipe deleted')
        return redirect('recipes:recipe_list')
    return render(request, 'recipes/delete_recipe.html', {'recipe': recipe})


class RecipeUpdateView(UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'recipes/edit_recipe.html'

    def get_success_url(self):
        return reverse_lazy('recipes:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = RecipeCategory.objects.all()
        return context

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.save()
        return super().form_valid(form)


def random_recipe(request):
    if request.user.is_authenticated:
        user_recipes = Recipe.objects.filter(user=request.user)
        if user_recipes.exists():
            random_recipe = choice(user_recipes)
            return redirect('recipes:detail', pk=random_recipe.pk)
        else:
            messages.success(request, f'You have no current recipes')
            return redirect('recipes:recipe_list')
    else:
        return redirect('login')

final_project/recipes/templates/recipes/add_recipe.html
{% extends 'recipes/base.html' %}

{% block style %}
    <style>
        /* Add your custom styles here */
        .container {
            margin-top: 20px;
        }
        #recipe_url {
            margin-bottom: 10px;
        }
        label {
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title text-center mb-4 text-primary">Add Recipe</h1>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <input class="form-control" type="text" name="recipe_url" id="recipe_url" placeholder="Enter Site Address">
                            </div>
                            <div class="form-group">
                                <label for="category">Select Recipe Category:</label>
                                <select class="form-control" name="category" id="category">
                                    {% for category in categories %}
                                        <option value="{{ category.id }}">{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="text-center">
                                <button class="btn btn-primary mt-2" type="submit">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

final_project/recipes/templates/recipes/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'recipe_site/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+zG2MZF0yeaFv4P7C2PL8ifw5ERn2hBJz7bxMf/" crossorigin="anonymous"></script>

    {% block style %} {% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <h1 class="navbar-brand">My Recipes</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'recipes:recipe_list' %}">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text">Hello {{ user.username }}</span>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor %}

{% endif %}
{% block body %}

{% endblock %}
</body>
</html>

final_project/recipes/templates/recipes/delete_recipe.html
{% extends 'recipes/base.html' %}
{% block body %}
    <h1>Delete Recipe</h1>
    <p>Are you sure you want to delete "{{ recipe.title }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Confirm Delete</button>
    </form>
{% endblock %}

final_project/recipes/templates/recipes/edit_recipe.html
{% extends 'recipes/base.html' %}
{% block style %}
     <style>
         .form-control {
             border: 2px solid;
         }
         .custom-select {
             border: 2px solid;
         }
        .custom-select:hover {
            border: 2px solid transparent;
            border-color: #007bff;
        }
    </style>
{% endblock %}
{% block body %}
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title text-center mb-4">Edit Recipe</h1>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_title">Title:</label>
                                {{ form.title.errors }}
                                <input type="text" name="title" id="id_title" class="form-control" value="{{ form.title.value }}">
                            </div>
                            <div class="form-group">
                                <label for="id_category">Category:</label>
                                {{ form.category.errors }}
                                <select name="category" id="id_category" class="form-control custom-select">
                                    <option value="" {% if not form.instance.category %}selected{% endif %}>-- Select Category --</option>
                                    {% for category in categories %}
                                    <option value="{{ category.pk }}" {% if form.instance.category == category %}selected{% endif %}>{{ category.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="id_recipe_image">Recipe Image:</label>
                                {{ form.recipe_image.errors }}
                                <input type="text" name="recipe_image" id="id_recipe_image" class="form-control" value="{{ form.recipe_image.value }}">
                            </div>
                            <div class="text-center mt-3">
                                <button class="btn btn-success" type="submit">Save Changes</button>
                                <a href="{% url 'recipes:detail' pk=form.instance.pk %}" class="btn btn-danger">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

final_project/recipes/templates/recipes/error.html
{% extends 'recipes/base.html' %}

{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="card-title text-center">Error</h5>
                </div>
                <div class="card-body">
                    <p>{{ error_message }}</p>
                    <div class="text-center">
                        <a href="{{ return_url }}" class="btn btn-primary">Return to main recipe page</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

final_project/recipes/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">{{ recipe.title }}</h1>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-4 h-100 d-flex flex-column">
                <div class="card-body">
                    <h2>Ingredients</h2>
                    <ul>
                        {% for recipe_ingredient in recipe_ingredients %}
                            <li>{{ recipe_ingredient.ingredient.name }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-4 h-100 d-flex flex-column">
                <div class="card-body">
                    <h2>Instructions</h2>
                    <ol>
                        {% for recipe_instruction in recipe_instructions %}
                            <li>{{ recipe_instruction.instruction.instruction }}</li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="text-center mb-5">
            <a href="{% url 'recipes:delete_recipe' pk=recipe.pk  %}" class="btn btn-danger btn-block">Delete Recipe</a>
            <a href="{% url 'recipes:edit_recipe' pk=recipe.pk  %}" class="btn btn-primary btn-block">Edit Recipe</a>
        </div>
    </div>
</div>

{% endblock %}

final_project/recipes/templates/recipes/recipe_list.html
{% extends 'recipes/base.html' %}
{% block style %}

{% endblock %}
{% block body %}
<body>
    <h1 class="card-title text-center mt-2 text-primary">My Cookbook</h1>
    <div class="container mt-3">
        <div class="row">
            <div class="col-md-4">
                <form method="GET" action="{% url 'recipes:recipe_list' %}" class="mt-3">
                    <div class="input-group">
                        <input type="text" class="form-control" name="ingredient" id="ingredient" placeholder="Filter by Ingredient">
                    </div>
                    <button type="submit" class="btn btn-primary">Filter</button>
                </form>
            </div>
            <div class="col-md-4">
                <form method="GET" action="{% url 'recipes:recipe_list' %}" class="mt-3">
                    <div class="form-group">
                        <select class="form-control" id="categorySelect" name="category">
                            <option value="" {% if not selected_category %}selected{% endif %}>Filter by Category</option>
                            {% for category in categories %}
                            <option value="{{ category.pk }}" {% if selected_category == category.pk %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary mt-1">Filter</button>
                </form>
            </div>
            <div class="col-md-4">
                <p class="mt-3">Can't decide what's for dinner?</p>
                <a href="{% url 'recipes:random_recipe' %}" class="btn btn-primary">Random Recipe</a>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <div class="row row-cols-1 row-cols-md-3">
            {% for recipe in recipe_list %}
            <div class="col mb-4 d-flex">
                <div class="card w-100">
                    <img class="card-img-top img-fluid" src="{{ recipe.recipe_image }}" alt="Recipe Image" style="object-fit: cover; height: 200px;">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title"><a href="{% url 'recipes:detail' pk=recipe.pk %}">{{ recipe.title }}</a></h5>
                        <p class="card-text flex-grow-1">{{ recipe.description }}</p>
                        <a href="{% url 'recipes:detail' pk=recipe.pk %}" class="btn btn-primary mt-auto">View Recipe</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% if is_paginated %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <!-- Include existing query parameters in pagination links -->
            <li class="page-item">
                <a class="page-link" href="?page=1{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&laquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&lsaquo;</a>
            </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            <li class="page-item {% if num == page_obj.number %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">{{ num }}</a>
            </li>
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&rsaquo;</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">&raquo;</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

</body>
{% endblock %}