final_project/final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('recipes/', include('recipes.urls')),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
]

urlpatterns += [
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final_project/recipes/urls.py
from django.urls import path
from . import views


app_name = 'recipes'
urlpatterns = [
    path('', views.RecipeList.as_view(), name="recipe_list"),
    path('<int:pk>/', views.RecipeDetail.as_view(), name='detail'),
    path('add_recipe/', views.add_recipe, name="add_recipe"),
    path('delete/<int:pk>', views.delete_recipe, name="delete_recipe"),
    path('edit/<int:pk>/', views.RecipeUpdateView.as_view(), name='edit_recipe'),
    path('random/', views.random_recipe, name='random_recipe'),
]

final_project/users/models.py
from django.db import models


# Create your models here.

final_project/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

final_project/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}! You are logged in!')
            return redirect('login')
        else:
            for error in form.errors:
                if 'password' in error.lower():
                    messages.error(request,
                                   f'Password error: Please use a combination of uppercase,'
                                   f' lowercase letters, numbers, and symbols.\n Ensure that passwords match.')
                    break
                if 'username' in error.lower():
                    messages.error(request,
                                   f'Username already taken. Please select new username.')
                    break
    else:
        form = RegistrationForm()
    return render(request, 'users/register.html', {'form': form})

final_project/users/templates/users/login.html
{% extends 'recipes/base.html' %}

{% block style %}
<style>
    .card {
        margin-top: 50px;
    }
</style>
{% endblock %}

{% block body %}
    {% if user.is_authenticated %}
        {% url 'recipes:recipe_list' as redirect_to %}
        <script>window.location.href = "{% url 'recipes:recipe_list' %}";</script>
    {% else %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5 class="card-title text-center">Login</h5>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="mb-2 row">
                                    <label class="col-md-4 col-form-label">{{ field.label_tag }}</label>
                                    <div class="col-md-4">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <button class="btn btn-primary" type="submit">Login</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <p class="text-center">Don't have an account? <a href="{% url 'register' %}" class="btn btn-primary">Register</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

final_project/users/templates/users/logout.html
<h1>You have been logged out!</h1>

final_project/users/templates/users/register.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'recipe_site/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+zG2MZF0yeaFv4P7C2PL8ifw5ERn2hBJz7bxMf/" crossorigin="anonymous"></script>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <h1 class="navbar-brand">Recipes App</h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'recipes:recipe_list' %}">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'recipes:add_recipe' %}">Add Recipe</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link navbar-text" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
 <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h5 class="card-title text-center">Register</h5>
                    </div>
                    <div class="card-body">
                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            <strong>There were errors in your registration:</strong>
                            <ul>
                                {% for error in form.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-{{ message.tags }}">
                                            {{ message }}
                                        </div>
                                    {% endfor %}

                                {% endif %}
                            </ul>
                        </div>
                    {% endif %}
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group mb-2">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <div class="text-center">
                                <button class="btn btn-primary" type="submit">SignUp</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>